version: '3.7'
services:
  node_service:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'

  mysql_service:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql-service:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data_postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
