version: '3.7'
services:
  notmysql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=rand
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass